version: "3.8"

services:
  postgres_mine:
    image: postgres:15
    container_name: postgres_blog
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog_network

  backend:
    build: ./backend
    container_name: blog_backend
    depends_on:
      - postgres_mine
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - blog_network

  frontend:
    build: ./frontend
    container_name: blog_frontend
    restart: always
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://backend:5000
    ports:
      - "3000:3000"
    networks:
      - blog_network

volumes:
  postgres_data:

networks:
  blog_network:
    driver: host
